### ISSUE TITLE
Why does an anaconda environment automatically open after I install this extension?

### ISSUE THREAD

**Issue by lknt** [franneck94/Vscode-Workspace-Formatter#3]
Why does an anaconda environment automatically open after I install this extension?
![image](https://github.com/franneck94/Vscode-Workspace-Formatter/assets/53924313/60bfcba0-0153-49f8-ae87-7799cf2b20ce)

**Comment by franneck94** [comment]
This is not related to that extension

**Comment by franneck94** [comment]
Maybe its related to your settings of which formatters are used?
